apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: GreenchClaw-home-pvc
  labels:
    app: GreenchClaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
