apiVersion: v1
kind: Service
metadata:
  name: GreenchClaw
  labels:
    app: GreenchClaw
spec:
  type: ClusterIP
  selector:
    app: GreenchClaw
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
