export const browserCoreExamples = [
  "GreenchClaw browser status",
  "GreenchClaw browser start",
  "GreenchClaw browser start --headless",
  "GreenchClaw browser stop",
  "GreenchClaw browser tabs",
  "GreenchClaw browser open https://example.com",
  "GreenchClaw browser focus abcd1234",
  "GreenchClaw browser close abcd1234",
  "GreenchClaw browser screenshot",
  "GreenchClaw browser screenshot --full-page",
  "GreenchClaw browser screenshot --ref 12",
  "GreenchClaw browser snapshot",
  "GreenchClaw browser snapshot --format aria --limit 200",
  "GreenchClaw browser snapshot --efficient",
  "GreenchClaw browser snapshot --labels",
];

export const browserActionExamples = [
  "GreenchClaw browser navigate https://example.com",
  "GreenchClaw browser resize 1280 720",
  "GreenchClaw browser click 12 --double",
  "GreenchClaw browser click-coords 120 340",
  'GreenchClaw browser type 23 "hello" --submit',
  "GreenchClaw browser press Enter",
  "GreenchClaw browser hover 44",
  "GreenchClaw browser drag 10 11",
  "GreenchClaw browser select 9 OptionA OptionB",
  "GreenchClaw browser upload /tmp/GreenchClaw/uploads/file.pdf",
  'GreenchClaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "GreenchClaw browser dialog --accept",
  'GreenchClaw browser wait --text "Done"',
  "GreenchClaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "GreenchClaw browser console --level error",
  "GreenchClaw browser pdf",
];
